// Code generated by dbus-codegen-go DO NOT EDIT.
package main

import (
	"context"
	"github.com/godbus/dbus/v5"
)

// Interface name constants.
const (
	InterfaceOrg_Example_Demo = "org.example.Demo"
)

// NewOrg_Example_Demo creates and allocates org.example.Demo.
func NewOrg_Example_Demo(object dbus.BusObject) *Org_Example_Demo {
	return &Org_Example_Demo{object}
}

// Org_Example_Demo implements org.example.Demo D-Bus interface.
type Org_Example_Demo struct {
	object dbus.BusObject
}

// WelcomeMessage calls org.example.Demo.WelcomeMessage method.
func (o *Org_Example_Demo) WelcomeMessage(ctx context.Context) (outputMessage string, err error) {
	err = o.object.CallWithContext(ctx, InterfaceOrg_Example_Demo+".WelcomeMessage", 0).Store(&outputMessage)
	return
}
